AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  actual-leave-ashwin

  Sample SAM Template for actual-leave-ashwin

Parameters:
  JWTSecret:
    Type: String
    NoEcho: True
    Description: JWT Secret for Leave Management API
    Default: "ashwin-leave-key"

Globals:
  Function:
    Timeout: 15
    LoggingConfig:
      LogFormat: JSON

Resources:
  AshwinLeaveTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ActualLeaveRequestsAshwin
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AshwinLeaveAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: LeaveManagementAPI
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: AshwinLeaveAuthorizer # Set default, overridden where needed
        Authorizers:
          AshwinLeaveAuthorizer:
            FunctionArn: !GetAtt AshwinLeaveAuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: "^Bearer [-0-9a-zA-Z._]*$" # Match Bearer token format

  AshwinLeaveAuthorizerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: lambdas/
      Handler: app.authorizer
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          JWT_SECRET: !Ref JWTSecret

  AshwinLeaveSubmitFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: lambdas/
      Handler: app.applyLeave
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AshwinLeaveTable
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref AshwinLeaveStateMachine
      Environment:
        Variables:
          TABLE_NAME: !Ref AshwinLeaveTable
          SES_EMAIL: "ashwin.dilip@antstack.io"
          STATE_MACHINE_ARN: !Ref AshwinLeaveStateMachine
      Events:
        ApplyLeave:
          Type: Api
          Properties:
            Path: /apply-leave
            Method: POST
            RestApiId: !Ref AshwinLeaveAPI
            Auth:
              Authorizer: AshwinLeaveAuthorizer # Explicitly use authorizer

  AshwinLeaveSendApprovalEmailFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: lambdas/
      Handler: app.sendApprovalEmail
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          SES_EMAIL: "ashwin.dilip@antstack.io"

  AshwinLeaveProcessApprovalFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: lambdas/
      Handler: app.processApproval
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
                - states:SendTaskFailure
              Resource: "*"
      Events:
        ProcessApproval:
          Type: Api
          Properties:
            Path: /process-approval
            Method: GET
            RestApiId: !Ref AshwinLeaveAPI
            Auth:
              Authorizer: NONE # Explicitly disable authorizer

  AshwinLeaveNotifyUserFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
    Properties:
      CodeUri: lambdas/
      Handler: app.notifyUser
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - AmazonSESFullAccess
      Environment:
        Variables:
          SES_EMAIL: "ashwin.dilip@antstack.io"

  AshwinLeaveStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-function.asl.json
      DefinitionSubstitutions:
        AshwinLeaveSendApprovalEmailFunctionArn: !GetAtt AshwinLeaveSendApprovalEmailFunction.Arn
        AshwinLeaveNotifyUserFunctionArn: !GetAtt AshwinLeaveNotifyUserFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref AshwinLeaveSendApprovalEmailFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AshwinLeaveNotifyUserFunction

Outputs:
  AshwinLeaveAPIEndpoint:
    Description: "API Gateway endpoint URL for Leave Management"
    Value: !Sub "https://${AshwinLeaveAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
